config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  root "home#index"

  devise_for :users

  devise_scope :user do
    get "users/sign_up", to: redirect("/")
  end

  resources :users do
    resources :portfolios, only: :show
  end

  resources :classrooms, except: [:destroy] do
    member do
      patch :toggle_trading
    end
    resources :grade_books, only: %i[show update] do
      member do
        post :finalize
      end
    end
    resources :students, except: %i[index show] do
      member do
        patch :reset_password
        patch :generate_password
      end
    end
    resources :classroom_enrollments, only: %i[create destroy] do
      member do
        patch :unenroll
      end
    end
  end

  namespace :admin do
    root "classrooms#index"
    resources :announcements
    resources :classrooms, except: [:destroy] do
      member do
        patch :toggle_archive
      end
    end
    resources :grades
    resources :portfolio_transactions, except: [:index]
    resources :schools
    resources :school_years
    resources :stocks
    resources :students do
      collection do
        post :import
        get :template
      end
      post "add_transaction"
      member do
        patch :restore
      end
    end
    resources :teachers
    resources :users
  end

  # Admin V2 - In-house admin implementation (dual-running with Administrate)
  namespace :admin_v2, path: "admin-new" do
    root "dashboard#index"

    # Component demo (development/testing only)
    resources :component_demo, only: %i[index show] do
      collection do
        get :form
      end
    end

    # Resource routes
    resources :announcements
    resources :classrooms, except: [:destroy] do
      member do
        patch :toggle_archive
      end
    end
    resources :grades
    resources :schools
    resources :school_years
    resources :stocks
    resources :students do
      collection do
        post :import
        get :template
      end
      member do
        patch :restore
        post :add_transaction
      end
    end
    resources :teachers do
      resource :deactivation, only: [:create], controller: "teachers/deactivations"
      resource :reactivation, only: [:create], controller: "teachers/reactivations"
    end
    resources :users
    resources :years
    resources :portfolio_transactions, except: [:index]
  end

  resources :orders do
    member do
      patch :cancel
    end
  end
  resources :portfolios, only: :show
  resources :stocks, only: %i[show index]
  resources :announcements, only: :show
end

app/models/teacher.rb
# frozen_string_literal: true

class Teacher < User
  has_many :teacher_classrooms, dependent: :destroy
  has_many :classrooms, through: :teacher_classrooms
end

app/controllers/admin/teachers_controller.rb
# frozen_string_literal: true

module Admin
  class TeachersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # need to create the new teacher by the admin
    def create
      temp_password = Devise.friendly_token.first(20)
      classroom_id = teacher_params[:classroom_id]
      classroom = Classroom.find_by(id: classroom_id)

      @teacher = Teacher.new(teacher_params.merge(password: temp_password))
      @teacher.classrooms << classroom if classroom

      unless @teacher.save
        return render :new, status: :unprocessable_content,
                            locals: { page: Administrate::Page::Form.new(dashboard, @teacher) }
      end

      @teacher.send_reset_password_instructions
      redirect_to admin_teachers_path, notice: t("teachers.create.notice")
    end

    private

    def teacher_params
      params.expect(teacher: %i[email name username classroom_id])
    end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin_v2/announcements_controller.rb
# frozen_string_literal: true

module AdminV2
  class AnnouncementsController < BaseController
    before_action :set_announcement, only: %i[show edit update destroy]

    def index
      sort_column = params[:sort].presence || "created_at"
      sort_direction = params[:direction] == "desc" ? :desc : :asc

      @announcements = Announcement.reorder(sort_column => sort_direction)

      @breadcrumbs = [
        { label: "Announcements" }
      ]
    end

    def show
      @breadcrumbs = [
        { label: "Announcements", path: admin_v2_announcements_path },
        { label: @announcement.title }
      ]
    end

    def new
      @announcement = Announcement.new
      @breadcrumbs = [
        { label: "Announcements", path: admin_v2_announcements_path },
        { label: "New Announcement" }
      ]
    end

    def edit
      @breadcrumbs = [
        { label: "Announcements", path: admin_v2_announcements_path },
        { label: @announcement.title, path: admin_v2_announcement_path(@announcement) },
        { label: "Edit" }
      ]
    end

    def create
      @announcement = Announcement.new(announcement_params)

      if @announcement.save
        redirect_to admin_v2_announcement_path(@announcement), notice: t(".notice")
      else
        @breadcrumbs = [
          { label: "Announcements", path: admin_v2_announcements_path },
          { label: "New Announcement" }
        ]
        render :new, status: :unprocessable_content
      end
    end

    def update
      if @announcement.update(announcement_params)
        redirect_to admin_v2_announcement_path(@announcement), notice: t(".notice")
      else
        @breadcrumbs = [
          { label: "Announcements", path: admin_v2_announcements_path },
          { label: @announcement.title, path: admin_v2_announcement_path(@announcement) },
          { label: "Edit" }
        ]
        render :edit, status: :unprocessable_content
      end
    end

    def destroy
      @announcement.destroy
      redirect_to admin_v2_announcements_path, notice: t(".notice")
    end

    private

    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    def announcement_params
      params.expect(announcement: %i[title content featured])
    end
  end
end

app/controllers/admin_v2/base_controller.rb
# frozen_string_literal: true

# Base controller for Admin V2 (in-house admin)
# All AdminV2 controllers inherit from this controller.
module AdminV2
  class BaseController < ApplicationController
    layout "admin_v2"

    before_action :authenticate_admin

    private

    def authenticate_admin
      redirect_to root_path, alert: t("application.access_denied.admin_required") unless current_user&.admin?
    end

    # Apply sorting to a collection based on params
    # @param collection [ActiveRecord::Relation] The base collection to sort
    # @param default [String] The default column to sort by
    # @return [ActiveRecord::Relation] The sorted collection
    def apply_sorting(collection, default:)
      sort_column = params[:sort].presence || default
      sort_direction = params[:direction] == "desc" ? :desc : :asc
      collection.reorder(sort_column => sort_direction)
    end
  end
end

app/controllers/admin_v2/classrooms_controller.rb
# frozen_string_literal: true

module AdminV2
  class ClassroomsController < BaseController
    before_action :set_classroom, only: %i[show edit update toggle_archive]

    def index
      @classrooms = apply_sorting(Classroom.all, default: "name")

      @breadcrumbs = [
        { label: "Classrooms" }
      ]
    end

    def show
      @breadcrumbs = [
        { label: "Classrooms", path: admin_v2_classrooms_path },
        { label: @classroom.name }
      ]
    end

    def new
      @classroom = Classroom.new

      @breadcrumbs = [
        { label: "Classrooms", path: admin_v2_classrooms_path },
        { label: "New Classroom" }
      ]
    end

    def edit
      @breadcrumbs = [
        { label: "Classrooms", path: admin_v2_classrooms_path },
        { label: @classroom.name, path: admin_v2_classroom_path(@classroom) },
        { label: "Edit" }
      ]
    end

    def create
      @classroom = Classroom.new(classroom_params)

      if @classroom.save
        redirect_to admin_v2_classroom_path(@classroom), notice: t(".notice")
      else
        @breadcrumbs = [
          { label: "Classrooms", path: admin_v2_classrooms_path },
          { label: "New Classroom" }
        ]
        render :new, status: :unprocessable_content
      end
    end

    def update
      if @classroom.update(classroom_params)
        redirect_to admin_v2_classroom_path(@classroom), notice: t(".notice")
      else
        @breadcrumbs = [
          { label: "Classrooms", path: admin_v2_classrooms_path },
          { label: @classroom.name, path: admin_v2_classroom_path(@classroom) },
          { label: "Edit" }
        ]
        render :edit, status: :unprocessable_content
      end
    end

    def toggle_archive
      authorize @classroom, :toggle_archive?
      @classroom.update!(archived: !@classroom.archived)
      flash[:notice] = @classroom.archived? ? "Classroom has been archived." : "Classroom has been activated."
      redirect_to admin_v2_classroom_path(@classroom)
    end

    private

    def set_classroom
      @classroom = Classroom.find(params.expect(:id))
    end

    def classroom_params
      params.expect(classroom: [:name, :trading_enabled, :school_year_id, { grade_ids: [] }])
    end
  end
end

app/controllers/admin_v2/component_demo_controller.rb
# frozen_string_literal: true

module AdminV2
  class ComponentDemoController < BaseController
    # rubocop:disable Metrics/MethodLength
    def index
      # Demo data for table component - apply sorting before limit
      @users = User.all

      # Apply sorting if params present
      if params[:sort].present?
        direction = params[:direction] == "desc" ? :desc : :asc
        @users = @users.order(params[:sort] => direction)
      end

      @users = @users.limit(10)

      # Demo data for show component
      @sample_user = User.first || User.new(
        email: "demo@example.com",
        name: "Demo User",
        admin: true,
        created_at: Time.current
      )

      # Demo breadcrumbs
      @breadcrumbs = [
        { label: "Components", path: admin_v2_component_demo_index_path },
        { label: "Demo" }
      ]

      # Demo table columns
      @columns = [
        { attribute: :id, label: "ID", sortable: true },
        { attribute: :email, label: "Email", sortable: true },
        { attribute: :name, label: "Name", sortable: true },
        { attribute: :admin, label: "Admin", sortable: true },
        { attribute: :created_at, label: "Created", sortable: true }
      ]

      # Demo filters
      @filters = [
        {
          name: :type,
          label: "User Type",
          options: [["All", ""], ["Admin", "admin"], ["Teacher", "teacher"], ["Student", "student"]]
        },
        {
          name: :status,
          label: "Status",
          options: [["All", ""], ["Active", "active"], ["Inactive", "inactive"]]
        }
      ]
    end
    # rubocop:enable Metrics/MethodLength

    def show
      @user = User.find(params[:id])
      @breadcrumbs = [
        { label: "Components", path: admin_v2_component_demo_index_path },
        { label: "User Details" }
      ]
    end

    def form
      @user = User.first || User.new(email: "", name: "", admin: false)

      # Add validation errors for demo purposes if requested
      if params[:show_errors] == "true"
        @user.errors.add(:email, "can't be blank")
        @user.errors.add(:name, "is too short (minimum is 3 characters)")
      end

      @breadcrumbs = [
        { label: "Components", path: admin_v2_component_demo_index_path },
        { label: "Form Builder Demo" }
      ]
    end
  end
end

app/controllers/admin_v2/dashboard_controller.rb
# frozen_string_literal: true

module AdminV2
  class DashboardController < BaseController
    def index
      # Dashboard will show overview of admin resources
    end
  end
end

app/controllers/admin_v2/grades_controller.rb
# frozen_string_literal: true

module AdminV2
  class GradesController < BaseController
    before_action :set_grade, only: %i[show edit update destroy]

    def index
      @grades = apply_sorting(Grade.all, default: "level")

      @breadcrumbs = [
        { label: "Grades" }
      ]
    end

    def show
      @breadcrumbs = [
        { label: "Grades", path: admin_v2_grades_path },
        { label: @grade.name }
      ]
    end

    def new
      @grade = Grade.new
      @breadcrumbs = [
        { label: "Grades", path: admin_v2_grades_path },
        { label: "New Grade" }
      ]
    end

    def edit
      @breadcrumbs = [
        { label: "Grades", path: admin_v2_grades_path },
        { label: @grade.name, path: admin_v2_grade_path(@grade) },
        { label: "Edit" }
      ]
    end

    def create
      @grade = Grade.new(grade_params)

      if @grade.save
        redirect_to admin_v2_grade_path(@grade), notice: t(".notice")
      else
        @breadcrumbs = [
          { label: "Grades", path: admin_v2_grades_path },
          { label: "New Grade" }
        ]
        render :new, status: :unprocessable_content
      end
    end

    def update
      if @grade.update(grade_params)
        redirect_to admin_v2_grade_path(@grade), notice: t(".notice")
      else
        @breadcrumbs = [
          { label: "Grades", path: admin_v2_grades_path },
          { label: @grade.name, path: admin_v2_grade_path(@grade) },
          { label: "Edit" }
        ]
        render :edit, status: :unprocessable_content
      end
    end

    def destroy
      @grade.destroy
      redirect_to admin_v2_grades_path, notice: t(".notice")
    end

    private

    def set_grade
      @grade = Grade.find(params[:id])
    end

    def grade_params
      params.expect(grade: %i[level name])
    end
  end
end

app/controllers/admin_v2/teachers/deactivations_controller.rb
# frozen_string_literal: true

module AdminV2
  module Teachers
    class DeactivationsController < BaseController
      before_action :set_teacher

      def create
        username = @teacher.username
        @teacher.discard
        redirect_back_or_to admin_v2_teachers_path, notice: t(".notice", username: username)
      end

      private

      def set_teacher
        @teacher = Teacher.find(params.expect(:teacher_id))
      end
    end
  end
end

app/controllers/admin_v2/teachers/reactivations_controller.rb
# frozen_string_literal: true

module AdminV2
  module Teachers
    class ReactivationsController < BaseController
      before_action :set_teacher

      def create
        username = @teacher.username
        @teacher.undiscard
        redirect_back_or_to admin_v2_teachers_path, notice: t(".notice", username: username)
      end

      private

      def set_teacher
        @teacher = Teacher.with_discarded.find(params.expect(:teacher_id))
      end
    end
  end
end

app/helpers/admin_v2/form_helper.rb
# frozen_string_literal: true

module AdminV2
  module FormHelper
    # Creates a form using the AdminV2::FormBuilder
    # Usage: admin_form_for @resource do |f|
    #          f.text_field :name
    #          f.email_field :email
    #          f.submit_button
    #        end
    def admin_form_for(record, options = {}, &)
      options[:builder] = AdminV2::FormBuilder
      options[:html] ||= {}
      options[:html][:class] = "space-y-6 #{options[:html][:class]}"

      form_with(model: record, scope: model_scope(record), url: form_url(record), **options, &)
    end

    private

    # Determines the model scope for the form (e.g., :admin_v2_announcement)
    def model_scope(record)
      return record.first.model_name.param_key if record.is_a?(Array)

      record.model_name.param_key
    end

    # Determines the form URL based on the record (handles both new and existing records)
    def form_url(record)
      if record.is_a?(Array)
        resource = record.last
        if resource.persisted?
          [:admin_v2, resource]
        else
          record.first.is_a?(Symbol) ? [record.first, :admin_v2, resource] : [:admin_v2, resource]
        end
      else
        resource = record
        resource.persisted? ? [:admin_v2, resource] : [:admin_v2, resource.class.model_name.collection]
      end
    end
  end
end

app/views/admin_v2/teachers/_form.html.erb
<%= form_with model: @teacher, url: @teacher.persisted? ? admin_v2_teacher_path(@teacher) : admin_v2_teachers_path, builder: AdminV2::FormBuilder, class: "space-y-6" do |f| %>
  <div class="bg-white shadow-sm ring-1 ring-gray-900/5 rounded-lg">
    <div class="px-6 py-6">
      <h3 class="text-lg font-medium text-gray-900 mb-6">Teacher Details</h3>

      <%= f.text_field :username,
                       label: "Username",
                       hint: "Unique username for the teacher",
                       placeholder: "johndoe" %>

      <%= f.text_field :email,
                       label: "Email",
                       hint: "Email address (required for account setup)",
                       placeholder: "teacher@example.com" %>

      <%= f.text_field :name,
                       label: "Full Name",
                       hint: "Teacher's full name",
                       placeholder: "John Doe" %>

      <%= f.collection_check_boxes :classroom_ids,
                                   Classroom.order(:name),
                                   :id,
                                   :name,
                                   label: "Classrooms",
                                   hint: "Select one or more classrooms to assign to this teacher" %>

      <% if @teacher.new_record? %>
        <div class="mt-6 pt-6 border-t border-gray-200">
          <p class="text-sm text-gray-600">
            <i class="fas fa-info-circle mr-1"></i>
            A temporary password will be generated and a password reset email will be sent to the teacher's email address.
          </p>
        </div>
      <% end %>
    </div>
  </div>

  <div class="flex items-center justify-between gap-x-4">
    <div class="flex items-center gap-x-4">
      <%= f.cancel_button "Cancel", url: @teacher.persisted? ? admin_v2_teacher_path(@teacher) : admin_v2_teachers_path %>
      <%= f.submit_button @teacher.persisted? ? "Update Teacher" : "Create Teacher" %>
    </div>
    <% if @teacher.discarded? %>
      <%= link_to "Permanently Delete",
                  admin_v2_teacher_path(@teacher),
                  data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to permanently delete this teacher? This action cannot be undone." },
                  class: "inline-flex items-center px-4 py-2 border border-red-300 shadow-sm text-sm font-medium rounded-md text-red-700 bg-white hover:bg-red-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500" %>
    <% end %>
  </div>
<% end %>

app/views/admin_v2/teachers/edit.html.erb
<div class="max-w-7xl mx-auto">
  <%= admin_breadcrumbs(@breadcrumbs) %>

  <h1 class="text-3xl font-bold text-gray-900 mb-8">Edit Teacher</h1>

  <%= render "form", teacher: @teacher %>
</div>

app/views/admin_v2/teachers/index.html.erb
<div class="max-w-7xl mx-auto">
  <%= admin_breadcrumbs(@breadcrumbs) %>

  <div class="bg-white shadow-sm ring-1 ring-gray-900/5 rounded-lg overflow-hidden">
    <div class="px-4 py-5 sm:px-6 border-b border-gray-200">
      <div class="flex justify-between items-center mb-4">
        <h3 class="text-lg font-semibold text-gray-900">Teachers</h3>
        <div class="flex gap-2">
          <%= link_to "New Teacher", new_admin_v2_teacher_path,
                      class: "inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700" %>
        </div>
      </div>

      <!-- Filter Tabs -->
      <% current_filter = current_discard_filter %>
      <div class="flex gap-1 border-b border-gray-200">
        <%= link_to "Active",
                    admin_v2_teachers_path,
                    class: "px-4 py-2 text-sm font-medium #{current_filter == :active ? 'text-blue-600 border-b-2 border-blue-600' : 'text-gray-500 hover:text-gray-700 hover:border-gray-300'}" %>
        <%= link_to "Deactivated",
                    admin_v2_teachers_path(discarded: true),
                    class: "px-4 py-2 text-sm font-medium #{current_filter == :discarded ? 'text-blue-600 border-b-2 border-blue-600' : 'text-gray-500 hover:text-gray-700 hover:border-gray-300'}" %>
        <%= link_to "All",
                    admin_v2_teachers_path(all: true),
                    class: "px-4 py-2 text-sm font-medium #{current_filter == :all ? 'text-blue-600 border-b-2 border-blue-600' : 'text-gray-500 hover:text-gray-700 hover:border-gray-300'}" %>
      </div>
    </div>

    <div class="overflow-x-auto">
      <table class="min-w-full divide-y divide-gray-300">
        <thead class="bg-gray-50">
          <tr>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
              <%= sort_link(:id, "ID") %>
            </th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
              <%= sort_link(:username, "Username") %>
            </th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
              <%= sort_link(:email, "Email") %>
            </th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
              <%= sort_link(:name, "Name") %>
            </th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
              <%= sort_link(:created_at, "Created At") %>
            </th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
              Status
            </th>
            <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
              <span class="sr-only">Actions</span>
            </th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-200 bg-white">
          <% if @teachers.any? %>
            <% @teachers.each do |teacher| %>
              <tr id="<%= dom_id(teacher) %>" class="hover:bg-gray-50 transition-colors">
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-900">
                  <%= teacher.id %>
                </td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-900">
                  <%= teacher.username %>
                </td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-900">
                  <%= teacher.email %>
                </td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-900">
                  <%= teacher.name %>
                </td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-900">
                  <%= teacher.created_at.strftime("%B %d, %Y") %>
                </td>
                <td class="whitespace-nowrap px-3 py-4 text-sm">
                  <% if teacher.discarded? %>
                    <span class="inline-flex items-center rounded-md bg-red-50 px-2 py-1 text-xs font-medium text-red-700 ring-1 ring-inset ring-red-600/10">Deactivated</span>
                  <% else %>
                    <span class="inline-flex items-center rounded-md bg-green-50 px-2 py-1 text-xs font-medium text-green-700 ring-1 ring-inset ring-green-600/20">Active</span>
                  <% end %>
                </td>
                <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                  <div class="flex justify-end gap-2">
                    <%= link_to "View", admin_v2_teacher_path(teacher), class: "text-blue-600 hover:text-blue-800" %>
                    <%= link_to "Edit", edit_admin_v2_teacher_path(teacher), class: "text-gray-600 hover:text-gray-800" %>
                    <% if teacher.discarded? %>
                      <%= link_to "Reactivate", admin_v2_teacher_reactivation_path(teacher),
                                  data: { turbo_method: :post, turbo_confirm: "Are you sure you want to reactivate this teacher?" },
                                  class: "text-green-600 hover:text-green-800" %>
                    <% else %>
                      <%= link_to "Deactivate", admin_v2_teacher_deactivation_path(teacher),
                                  data: { turbo_method: :post, turbo_confirm: "Are you sure you want to deactivate this teacher?" },
                                  class: "text-red-600 hover:text-red-800" %>
                    <% end %>
                  </div>
                </td>
              </tr>
            <% end %>
          <% else %>
            <tr>
              <td colspan="7" class="px-3 py-12 text-center text-sm text-gray-500">
                <div class="flex flex-col items-center">
                  <i class="fas fa-inbox text-4xl text-gray-300 mb-3"></i>
                  <p class="font-medium">No records found</p>
                  <p class="text-gray-400 mt-1">No teachers found. Create your first teacher to get started.</p>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin_v2/teachers/new.html.erb
<div class="max-w-7xl mx-auto">
  <%= admin_breadcrumbs(@breadcrumbs) %>

  <h1 class="text-3xl font-bold text-gray-900 mb-8">New Teacher</h1>

  <%= render "form", teacher: @teacher %>
</div>

app/views/admin_v2/teachers/show.html.erb
<div class="max-w-7xl mx-auto">
  <%= admin_breadcrumbs(@breadcrumbs) %>

  <div class="bg-white shadow-sm ring-1 ring-gray-900/5 rounded-lg mb-6">
    <div class="px-6 py-6">
      <div class="flex items-center justify-between mb-6">
        <div class="flex items-center gap-3">
          <h2 class="text-2xl font-bold text-gray-900"><%= @teacher.username %></h2>
          <% if @teacher.discarded? %>
            <span class="inline-flex items-center rounded-md bg-red-50 px-2 py-1 text-xs font-medium text-red-700 ring-1 ring-inset ring-red-600/10">Deactivated</span>
          <% else %>
            <span class="inline-flex items-center rounded-md bg-green-50 px-2 py-1 text-xs font-medium text-green-700 ring-1 ring-inset ring-green-600/20">Active</span>
          <% end %>
        </div>
        <div class="flex gap-3">
          <%= link_to edit_admin_v2_teacher_path(@teacher),
                      class: "inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50" do %>
            <i class="fas fa-edit -ml-1 mr-2 h-5 w-5 text-gray-500"></i>
            Edit
          <% end %>
          <% if @teacher.discarded? %>
            <%= link_to admin_v2_teacher_reactivation_path(@teacher),
                        data: { turbo_method: :post, turbo_confirm: "Are you sure you want to reactivate this teacher?" },
                        class: "inline-flex items-center px-4 py-2 border border-green-300 shadow-sm text-sm font-medium rounded-md text-green-700 bg-white hover:bg-green-50" do %>
              <i class="fas fa-check-circle -ml-1 mr-2 h-5 w-5 text-green-500"></i>
              Reactivate
            <% end %>
            <%= link_to admin_v2_teacher_path(@teacher),
                        data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to permanently delete this teacher? This action cannot be undone." },
                        class: "inline-flex items-center px-4 py-2 border border-red-300 shadow-sm text-sm font-medium rounded-md text-red-700 bg-white hover:bg-red-50" do %>
              <i class="fas fa-trash -ml-1 mr-2 h-5 w-5 text-red-500"></i>
              Permanently Delete
            <% end %>
          <% else %>
            <%= link_to admin_v2_teacher_deactivation_path(@teacher),
                        data: { turbo_method: :post, turbo_confirm: "Are you sure you want to deactivate this teacher?" },
                        class: "inline-flex items-center px-4 py-2 border border-red-300 shadow-sm text-sm font-medium rounded-md text-red-700 bg-white hover:bg-red-50" do %>
              <i class="fas fa-trash -ml-1 mr-2 h-5 w-5 text-red-500"></i>
              Deactivate
            <% end %>
          <% end %>
        </div>
      </div>

      <%= admin_show_attributes(
            @teacher,
            attributes: %i[id username email name created_at updated_at]
          ) %>

      <!-- Associated Classrooms -->
      <% if @teacher.classrooms.any? %>
        <div class="mt-6 pt-6 border-t border-gray-200">
          <h3 class="text-sm font-medium text-gray-500 mb-3">Classrooms</h3>
          <ul class="space-y-2">
            <% @teacher.classrooms.each do |classroom| %>
              <li class="text-sm text-gray-900">
                <%= classroom.name %>
              </li>
            <% end %>
          </ul>
        </div>
      <% else %>
        <div class="mt-6 pt-6 border-t border-gray-200">
          <p class="text-sm text-gray-500">No classrooms assigned to this teacher yet.</p>
        </div>
      <% end %>
    </div>
  </div>

  <div class="flex gap-3">
    <%= link_to "Back to Teachers", admin_v2_teachers_path,
                class: "inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50" %>
  </div>
</div>